/** Canonical public-schema tables. Keep in lockstep with 0001_init.sql. */
export const PUBLIC_TABLES = [
  "tenants",
  "profiles",
  "events",
  "event_roles",
  "teams",
  "team_members",
  "milestones",
  "check_ins",
  "milestone_status",
  "commits",
  "api_calls",
  "rubric_criteria",
  "judge_assignments",
  "judge_conflicts",
  "scores",
  "calibration_samples",
  "calibration_results",
  "pairwise_votes",
  "team_ratings",
  "ai_reviews",
  "results",
  "judge_reliability",
  "discussion_flags",
  "judge_notes",
  "ai_review_feedback",
  "sponsors",
  "challenge_tracks",
  "team_tracks",
  "schedule_items",
  "messages",
  "announcement_reads",
  "mentors",
  "mentor_slots",
  "talent_profiles",
  "recruiter_orgs",
  "recruiter_access_log",
  "alumni_posts",
  "intro_requests",
  "consent_events",
  "erasure_requests",
] as const;

export type PublicTable = (typeof PUBLIC_TABLES)[number];

export const TABLES_WITHOUT_TENANT_ID: PublicTable[] = ["tenants"];
